# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
author: Saroj Mishra - sarmishra
title: My Personal Blog 
email: saroj.mishra773@gmail.com
description: This is the part how iam study and what i know. #> # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sarmishra.github.io" # the base hostname & protocol for your site, e.g. http://example.com
preview_image_url: https://avatars3.githubusercontent.com/u/9898138?s=460&v=4
twitter_username: SarMishra33
github_username: sarmishra
linkedin_username: saroj-mishra-135842136
facebook: 
        appid: 2104120559821260
so_nickname: saroj-mishra
so_uid: 7942617
github:
  repository_name: sarmishra
  project_tagline: Day to day Activities
# Build settings
highlighter: rouge
paginate: 5
paginate_path: "/blog/page:num"
markdown: kramdown
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-last-modified-at
exclude:
  - Gemfile
  - Gemfile.lock
